_G.SECOND_MS = 1000
_G.MINUTE_MS = _G.SECOND_MS * 60
_G.HOUR_MS   = _G.MINUTE_MS * 60
_G.DAY_MS    = _G.HOUR_MS * 24
_G.WEEK_MS   = _G.DAY_MS * 7


_G.MINUTE = 60
_G.HOUR  = _G.MINUTE * 60
_G.DAY   = _G.HOUR * 24
_G.WEEK  = _G.DAY * 7

-- skynet中，一个时间单位是10毫秒
_G.SKYNET_UNIT    = 1
_G.SKYNET_SECOND  = _G.SKYNET_UNIT * 100
_G.SKYNET_MINUTE  = _G.SKYNET_SECOND * 60
_G.SKYNET_HOUR    = _G.SKYNET_MINUTE * 60
_G.SKYNET_DAY     = _G.SKYNET_HOUR * 24
_G.SKYNET_WEEK    = _G.SKYNET_DAY * 7


_G.EVENT_MSG = {
    EVENT_PLAYER_ENTER = 1,
    EVENT_PLAYER_LEAVE = 2
}


_G.TIME_WHELL_TASK = {
    TASK_KICK_PLAYER = 1
}
